{% set name = "torch-lr-finder" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: d659725028e1ab860deeabe01f445e07f758285c524c8720bd9cc3f39343c778

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - matplotlib-base
    - numpy
    - packaging
    - python
    - pytorch >=0.4.1
    - tqdm

# Upstream tests skipped due to missing task package in main channel
test:
  imports:
    - torch_lr_finder
    - torch_lr_finder.lr_finder
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/davidtvs/pytorch-lr-finder
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pytorch implementation of the learning rate range test
  description: |
    The learning rate range test is a test that provides valuable information about the optimal learning rate. 
    During a pre-training run, the learning rate is increased linearly or exponentially between two boundaries. 
    The low initial learning rate allows the network to start converging and as the learning rate is increased 
    it will eventually be too large and the network will diverge.
  dev_url: https://github.com/davidtvs/pytorch-lr-finder
  doc_url: https://github.com/davidtvs/pytorch-lr-finder

extra:
  recipe-maintainers:
    - dholth
